# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.12.1"
  python_check_max: "3.14"
  cargo_wrapper: cargo-auditable-wrapper${{ ".sh" if unix else ".bat" }}

package:
  name: ast-serialize
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ast-serialize/ast_serialize-${{ version }}.tar.gz
  sha256: 5285a390caf1c44368ae270f037f797b91427d138b7d43cad0f1fda4c83518d9

build:
  number: 0
  skip: is_abi3 and not is_python_min
  python:
    version_independent: ${{ is_abi3 }}
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO: ${{ cargo_wrapper }}
      PYTHONIOENCODING: utf-8
      PYTHONLEGACYTEXTENCODING: utf-8
    content:
      - if: win
        then:
          # otherwise fails with:
          #  path too long:
          #    '%BUILD_PREFIX%/.cargo/git/checkouts/(~180 characters).snap'; class=Filesystem (30)
          - set CARGO_HOME=c:\.cg
          - copy "%RECIPE_DIR%\${{ cargo_wrapper }}" "%BUILD_PREFIX%\Library\bin\${{ cargo_wrapper }}"
        else:
          - cp "${RECIPE_DIR}/${{ cargo_wrapper }}" "${BUILD_PREFIX}/bin/"
          - chmod 755 "${BUILD_PREFIX}/bin/${{ cargo_wrapper }}"
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - cargo-auditable
    - cargo-bundle-licenses
  host:
    - maturin >=1.9,<2.0
    - pip
    - python
    - if: is_abi3
      then:
        - python-abi3
        - python ${{ python_min }}.*
  run:
    - if: is_abi3
      then:
        - python >=${{ python_min }}
      else:
        - python

tests:
  - package_contents:
      strict: true
      files:
        - etc/conda/test-files/ast-serialize/**
      site_packages:
        - ast_serialize/**
        - ast_serialize-${{ version }}.dist-info/**
  - python:
      imports: ast_serialize
      pip_check: true
      python_version:
        - if: is_abi3
          then:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
          else:
            - "*"
  - files:
      source:
        - test_ast_serialize.py
    requirements:
      run:
        - pytest
        - if: is_abi3
          then:
            - abi3audit
            - python ${{ python_min }}.*
    script:
      - python test_ast_serialize.py
      - if: is_abi3
        then:
          - if: unix
            then: abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} "${SP_DIR}/ast_serialize/ast_serialize.abi3.so"
            else: abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} "%SP_DIR%\ast_serialize\ast_serialize.pyd"

about:
  summary: Python bindings for mypy AST serialization
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/ast-serialize
  repository: https://github.com/mypyc/ast_serialize

extra:
  recipe-maintainers:
    - conda-forge/mypy
    - bollwyvl
